version: 2

project_name: eddie

builds:
  - id: eddie
    main: ./cmd/eddie
    binary: eddie
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}
      - -X main.date={{.Date}}
      - -X main.revision={{.ShortCommit}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
